name: 'Deploy BPMN models'
description: 'GitHub Action for automated deployment of BPMN models to a Camunda cluster'
author: 'Kristoffer Högberg'

inputs:
  connection_type:
    description: 'Choose: cloud or self-managed'
    required: true
  bpmn_models_source:
    description: 'Path to BPMN models'
    required: true
  zeebe_client_id:
    description: 'Zeebe client id'
    required: true
  zeebe_client_secret:
    description: 'Zeebe client secret'
    required: true
  cluster_id:
    description: 'Camunda cloud cluster id (Camunda cloud only)'
    required: false
  cluster_region:
    description: 'Camunda cluster region (Camunda cloud only)'
    required: false
  oauth_url:
    description: 'Authentication url (self-managed only)'
    required: false
  host_name:
    description: 'Camunda cluster hostname (self-managed only)'
    required: false
  port:
    description: 'Camunda cluster port (self-managed only - typically 443)'
    required: false
  audience:
    description: 'Zeebe client audience (self-managed only)'
    required: false

runs:
  using: 'node20'
  main: 'dist/comp/index.js'

branding:
  icon: 'activity'
  color: 'green'
