name: 'Deploy BPMN models'
description: 'GitHub Action for automated deployment of BPMN models to a Camunda cluster'
author: 'Kristoffer Högberg'

inputs:
  connection_type:
    description: 'Choose: cloud or self-managed'
    required: true
  source:
    description: 'Path to BPMN models'
    required: true
  zeebe_client_id:
    description: 'Zeebe client id'
    required: true
  zeebe_client_secret:
    description: 'Zeebe client secret'
    required: true
  cluster_id:
    description: 'Camunda cloud cluster id'
    required: false
  oauth_url:
    description: 'Authentication url'
    required: false
  host_name:
    description: 'The self-manged cluster host name'
    required: false
  port:
    description: 'The self-managed cluster port (typically 443)'
    required: false
  audience:
    description: 'Zeebe client audience'
    required: false

runs:
  using: 'node20'
  main: 'dist/comp/index.js'

branding:
  icon: 'activity'
  color: 'green'
